<a href="https://colab.research.google.com/github/Ronald023/Topicos/blob/main/3er_parcial_parte_practica.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>



> Aggiungi citazione
#Tercer Parcial topicos


In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import GridSearchCV
!pip install pyreadstat
import pyreadstat

from google.colab import files # Para cargar archivos en google colab
uploaded = files.upload()



     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.8/2.8 MB 9.1 MB/s eta 0:00:00


Saving D. MENORES.txt to D. MENORES.txt


In [ ]:
import io
tabla = pd.read_csv(io.BytesIO(uploaded['D. MENORES.txt']), sep = "\t", index_col=0, encoding='latin-1') # Try using tab as delimiter
tabla.head(4)

Nro_encuesta  Secuencia_encuesta  Secuencia_p  Orden  P51  P52  \
Directorio                                                                   
447                  247                   4            1      4    4  5.0   
17255                247                   3            1      3    1  NaN   
373                  247                   5            1      5    1  NaN   
373                  247                   4            1      4    1  NaN   

           P52s1  P53  P54  P55  ...  P8582s3  P8582s4  P8582s11  P8582s6  \
Directorio                       ...                                        
447          NaN  NaN  NaN    1  ...      NaN      NaN       NaN      NaN   
17255        NaN  1.0  4.0    1  ...      NaN      NaN       NaN      NaN   
373          NaN  4.0  4.0    1  ...      NaN      NaN       NaN      NaN   
373          NaN  4.0  4.0    1  ...      NaN      NaN       NaN      NaN   

            P8582s7  P8582s9  P8582s12  P8582s10  P8582s10a1        Fex_c  
Directorio                                                                 
447             NaN      NaN       NaN       NaN         NaN  1454.129389  
17255           NaN      NaN       NaN       NaN         NaN   663.046128  
373             NaN      NaN       NaN       NaN         NaN  1925.021859  
373             NaN      NaN       NaN       NaN         NaN  1925.021859  

[4 rows x 52 columns]

Utilice las variables de las columnas "P51", "P52", "P55", "P56", "P57", "P6159s8",
"P6163s8", "P6161" y "P6161s1". En el análisis se deben eliminar las filas con datos
faltantes de la columna "P52". También se debe tener en cuenta que los valores faltantes de
las columnas "P6159s8" y "P6163s8" denotan que la madre y el padre sí realizan alguna
actividad con el menor, respectivamente.

In [ ]:
df = tabla[["P51", "P52", "P55", "P56", "P57", "P6159s8","P6163s8", "P6161", "P6161s1"]]
df_sin_faltantes = df.dropna(subset=['P52'])

df_sin_faltantes['P6159s8'] = df_sin_faltantes['P6159s8'].fillna(1)
df_sin_faltantes['P6163s8'] = df_sin_faltantes['P6163s8'].fillna(1)

df_sin_faltantes.head(4)

df_sin_faltantes["P6161"].head(5)

<ipython-input-36-b3b4f42028bf>:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_sin_faltantes['P6159s8'] = df_sin_faltantes['P6159s8'].fillna(1)
<ipython-input-36-b3b4f42028bf>:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_sin_faltantes['P6163s8'] = df_sin_faltantes['P6163s8'].fillna(1)


Directorio
447     1
226     1
224     1
215     1
1084    1
Name: P6161, dtype: int64

Tome un conjunto de datos de entrenamiento y de validación (del 20%), teniendo en cuenta
que las entradas corresponden a las variables de las columnas "P51", "P52", "P55", "P56",
"P57", "P6159s8" y "P6163s8", y, la salida es la variable "P6161".

In [ ]:
x = df_sin_faltantes.drop(["P6161", "P6161s1"], axis=1) # Variables explicativas
y = df_sin_faltantes["P6161"] # Variable respuesta
trainX, testX, trainY, testY = train_test_split(x, y, test_size = 0.2)


Implemente una red neuronal multicapa. Recuerde que todas las variables de entrada son
cualitativas, por lo tanto, pueden transformarlas a variables tipo dummie. Además, se trata
de una red de clasificación ya que la variable de la columna "P6161" es cualitativa: debe
usar la función MLPClassifier.

In [ ]:
sc=StandardScaler()
scaler = sc.fit(trainX)
trainX_scaled = scaler.transform(trainX) # Estandarizado los datos de entrenamiento para las variables explicativas
testX_scaled = scaler.transform(testX) # Estararizando los datos datos para las variables explicativas

In [ ]:
mlp_clf = MLPClassifier(hidden_layer_sizes = (100, 100, 100, 100, 100, 100, 100), #  MLPClassifier: Percentrón multicapa para clasificación
                        max_iter = 1000, activation = 'logistic',
                        solver = 'sgd')
mlp_clf.fit(trainX, trainY) # Entrenamos una red neuronal

MLPClassifier(activation='logistic',
              hidden_layer_sizes=(100, 100, 100, 100, 100, 100, 100),
              max_iter=1000, solver='sgd')

In [ ]:
y_pred = mlp_clf.predict(testX)
y_pred


array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,

In [ ]:
accuracy_score(testY, y_pred)

0.8091743119266055

In [ ]:
y_pred = mlp_clf.predict(testX)
print('Accuracy: {:.2f}'.format(accuracy_score(testY, y_pred)))

Accuracy: 0.81


## Implemente los siguientes algoritmos con entradas que corresponden a las variables de lascolumnas "P51", "P52", "P55", "P56", "P57", "P6159s8" y "P6163s8", y, con salida el variable "P6161":

A. Random Forest:
RandomForestClassifier(n_estimators=100, random_state=42)
B. Clasificador Naive Bayes:
GaussianNB()
C. Máquina de Soporte vectorial:
svm.SVC(decision_function_shape='ovr', kernel = "rbf", degree = 3)
Los argumentos escogidos de las anteriores funciones, en lo posible, deben buscar el mejor
ajuste con respecto a la precisión o exactitud, un balance adecuado de las predicciones de
todos los valores de acuerdo con la matriz de confusión y una curva de pérdida (para los
modelos que se puede construir) con un comportamiento adecuado.

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

# Escalado de los datos (opcional, pero útil para SVM)
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

### A. Random Forest

In [ ]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# Definir el modelo
rf_model = RandomForestClassifier(n_estimators=100, random_state=42)

# Entrenar el modelo
rf_model.fit(X_train, y_train)

# Hacer predicciones
y_pred_rf = rf_model.predict(X_test)

# Evaluar el modelo
accuracy_rf = accuracy_score(y_test, y_pred_rf)
conf_matrix_rf = confusion_matrix(y_test, y_pred_rf)
class_report_rf = classification_report(y_test, y_pred_rf)

print("Random Forest Classifier")
print(f"Accuracy: {accuracy_rf}")
print("Confusion Matrix:")
print(conf_matrix_rf)
print("Classification Report:")
print(class_report_rf)

Random Forest Classifier
Accuracy: 0.8165137614678899
Confusion Matrix:
[[434   6]
 [ 94  11]]
Classification Report:
              precision    recall  f1-score   support

           1       0.82      0.99      0.90       440
           2       0.65      0.10      0.18       105

    accuracy                           0.82       545
   macro avg       0.73      0.55      0.54       545
weighted avg       0.79      0.82      0.76       545



### B. Clasificador Naive Bayes

In [ ]:
from sklearn.naive_bayes import GaussianNB

# Definir el modelo
nb_model = GaussianNB()

# Entrenar el modelo
nb_model.fit(X_train, y_train)

# Hacer predicciones
y_pred_nb = nb_model.predict(X_test)

# Evaluar el modelo
accuracy_nb = accuracy_score(y_test, y_pred_nb)
conf_matrix_nb = confusion_matrix(y_test, y_pred_nb)
class_report_nb = classification_report(y_test, y_pred_nb)

print("Naive Bayes Classifier")
print(f"Accuracy: {accuracy_nb}")
print("Confusion Matrix:")
print(conf_matrix_nb)
print("Classification Report:")
print(class_report_nb)

Naive Bayes Classifier
Accuracy: 0.7743119266055046
Confusion Matrix:
[[397  43]
 [ 80  25]]
Classification Report:
              precision    recall  f1-score   support

           1       0.83      0.90      0.87       440
           2       0.37      0.24      0.29       105

    accuracy                           0.77       545
   macro avg       0.60      0.57      0.58       545
weighted avg       0.74      0.77      0.75       545



### C. Máquina de Soporte Vectorial (SVM)

In [ ]:
from sklearn import svm

# Definir el modelo
svm_model = svm.SVC(decision_function_shape='ovr', kernel='rbf', degree=3)

# Entrenar el modelo
svm_model.fit(X_train, y_train)

# Hacer predicciones
y_pred_svm = svm_model.predict(X_test)

# Evaluar el modelo
accuracy_svm = accuracy_score(y_test, y_pred_svm)
conf_matrix_svm = confusion_matrix(y_test, y_pred_svm)
class_report_svm = classification_report(y_test, y_pred_svm)

print("Support Vector Machine Classifier")
print(f"Accuracy: {accuracy_svm}")
print("Confusion Matrix:")
print(conf_matrix_svm)
print("Classification Report:")
print(class_report_svm)


Support Vector Machine Classifier
Accuracy: 0.8165137614678899
Confusion Matrix:
[[435   5]
 [ 95  10]]
Classification Report:
              precision    recall  f1-score   support

           1       0.82      0.99      0.90       440
           2       0.67      0.10      0.17       105

    accuracy                           0.82       545
   macro avg       0.74      0.54      0.53       545
weighted avg       0.79      0.82      0.76       545



In [ ]:
import matplotlib.pyplot as plt
from sklearn.model_selection import learning_curve

def plot_learning_curve(estimator, title, X, y, cv=None, n_jobs=None, train_sizes=np.linspace(.1, 1.0, 5)):
    plt.figure()
    plt.title(title)
    plt.xlabel("Training examples")
    plt.ylabel("Score")
    train_sizes, train_scores, test_scores = learning_curve(estimator, X, y, cv=cv, n_jobs=n_jobs, train_sizes=train_sizes)
    train_scores_mean = np.mean(train_scores, axis=1)
    train_scores_std = np.std(train_scores, axis=1)
    test_scores_mean = np.mean(test_scores, axis=1)
    test_scores_std = np.std(test_scores, axis=1)
    plt.grid()

    plt.fill_between(train_sizes, train_scores_mean - train_scores_std, train_scores_mean + train_scores_std, alpha=0.1, color="r")
    plt.fill_between(train_sizes, test_scores_mean - test_scores_std, test_scores_mean + test_scores_std, alpha=0.1, color="g")
    plt.plot(train_sizes, train_scores_mean, 'o-', color="r", label="Training score")
    plt.plot(train_sizes, test_scores_mean, 'o-', color="g", label="Cross-validation score")
    plt.legend(loc="best")
    return plt

# Curva de aprendizaje para Random Forest
plot_learning_curve(rf_model, "Learning Curves (Random Forest)", X_train, y_train, cv=5)
plt.show()

# Curva de aprendizaje para SVM
plot_learning_curve(svm_model, "Learning Curves (SVM)", X_train, y_train, cv=5)
plt.show()

# Curva de aprendizaje para NB
plot_learning_curve(nb_model, "Learning Curves (NB)", X_train, y_train, cv=5)
plt.show()



Encuentre, de acuerdo con las predicciones del mejor modelo de acuerdo con el ítem
anterior, los valores de las variables de las columnas "P51", "P52", "P55", "P56", "P57",
"P6159s8" y "P6163s8" qué menores de edad no ha recibido citas de control de
crecimiento y desarrollo.

## Encuentre, de acuerdo con las predicciones del mejor modelo de acuerdo con el ítem
anterior, los valores de las variables de las columnas "P51", "P52", "P55", "P56", "P57",
"P6159s8" y "P6163s8" qué menores de edad no ha recibido citas de control de
crecimiento y desarrollo.

In [ ]:
nb_model = GaussianNB()
nb_model.fit(X_train, y_train)

# Hacer predicciones con el modelo entrenado
y_pred = nb_model.predict(X_test)

# Evaluar el modelo
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
class_report = classification_report(y_test, y_pred)

print("Naive Bayes Classifier")
print(f"Accuracy: {accuracy}")
print("Confusion Matrix:")
print(conf_matrix)
print("Classification Report:")
print(class_report)

# Usar el modelo para predecir en todo el conjunto de datos x
y_pred_full = nb_model.predict(scaler.transform(x))

# Añadir las predicciones como una nueva columna al DataFrame original
x['Pred_P6161'] = y_pred_full

# Filtrar los menores de edad que no han recibido citas de control (Pred_P6161 == 0)
no_control = x[x['Pred_P6161'] == 0]

# Seleccionar las columnas relevantes
result = no_control[["P51", "P52", "P55", "P56", "P57", "P6159s8", "P6163s8"]]

# Mostrar el resultado
print("Menores de edad que no han recibido citas de control de crecimiento y desarrollo:")
print(result)


/usr/local/lib/python3.10/dist-packages/sklearn/base.py:432: UserWarning: X has feature names, but GaussianNB was fitted without feature names
  warnings.warn(


ValueError: X has 8 features, but GaussianNB is expecting 7 features as input.